### ISSUE TITLE
MikroOrm 5 support

### ISSUE THREAD

**Issue by vincentwinkel** [SoftwareBrothers/adminjs-mikroorm#11]
Can you please add the support of MikroOrm 5?

**Comment by rubiin** [comment]
https://github.com/SoftwareBrothers/adminjs-mikroorm/pull/10 this should do

**Comment by MaksymVynohradovDA** [comment]
Hi! @vincentwinkel @rubiin @dziraf  any news? Now I constantly receive "NoResourceAdapterError: There are no adapters supporting one of the resource you provided"
