### ISSUE TITLE
OneToMany Relationship

### ISSUE THREAD

**Issue by pxviet1997** [SoftwareBrothers/adminjs-mikroorm#21]
Hello,

I have an entity called `Artwork` that has an OneToMany relationship with another entity `ArtworkImage`. I read in the doc that OneToMany relationship can still be achieved through custom components and hooks. What exactly does it mean here? Can you give me an example?

I am setting up AdminJS with Fastify and Mikroorm

**Comment by dziraf** [comment]
It basically means you would have to create a custom action:
https://docs.adminjs.co/basics/action#creating-custom-actions
which would fetch ArtworkImages based on your requirements and a custom component:
https://docs.adminjs.co/ui-customization/writing-your-own-components
which would display the list of images in your desired place. Creating and updating these resources might be more difficult though.

**Comment by pxviet1997** [comment]
> It basically means you would have to create a custom action: https://docs.adminjs.co/basics/action#creating-custom-actions which would fetch ArtworkImages based on your requirements and a custom component: https://docs.adminjs.co/ui-customization/writing-your-own-components which would display the list of images in your desired place. Creating and updating these resources might be more difficult though.

<img width="1512" alt="Screenshot 2023-05-31 at 21 09 24" src="https://github.com/SoftwareBrothers/adminjs-mikroorm/assets/56182628/4d0c3733-0085-43d0-a178-d304a70e484d">
@dziraf  In my case, I would want to display the ArtworkImage in this list of Artwork, where the column Images is (which is the property with OneToMany relationship). Then how should I proceed?
(thank you for your reply! you are the first one who reply since I raise this question everywhere!)

**Comment by pxviet1997** [comment]
@dziraf nevermind, I got it! Thank you so much for the info!
